const locationsindorchester = [
"Acland Road",
"Albert Road",
"Allington Road",
"Antelope Walk",
"Brewery Square",
"Charles Street",
"Church Street",
"Colliton Street & Colliton Walk",
"Cornwall Road",
"Culliford Road (to bridge)",
"Durngate Street",
"Fairfield Road",
"Friary Lane",
"Glyde Path Road",
"Hardye Arcade",
"High East Street",
"High West Street",
"Icen Way",
"Linden Avenue",
"Maumbury Road (as far as Fairfield Road)",
"Nappers Mite",
"New Street",
"North Square",
"Northernhay",
"Prince of Wales Road (To Culliford Road junction)",
"Princes Street",
"South Street",
"South Walks",
"The Grove",
"The Mews",
"Trinity Street",
"Tudor Arcade",
"Weymouth Avenue",
"Wollaston Road",
"York Road"
]

export default locationsindorchester;