const records = [{
        id: 'alice',
        items: [{1: "tiktok"},{2: "youtube"}, {3: "reddit"}]
    },
    {
        id: 'bob',
        items: [{1:"twitter"},{2: "discord"}, {3: "email"}],
    }, // oftt is missign on purpose
    {
        id:"doer",
        items:[{1: "vpcy"}]
    },
    {
        id:"hlvs",
        items:["dgvx"]
    },
    {
        id:"uipq",
        items:["dkyg"]
    },
    {
        id:"xyda",
        items:["cjba"]
    },
    {
        id:"heep",
        items:["nbpq"]
    },
    {
        id:"dzrn",
        items:["sksd"]
    },
    {
        id:"oirx",
        items:["ygqh"]
    },
    {
        id:"cdkx",
        items:["xugh"]
    },
    {
        id:"mexk",
        items:["mwfx"]
    },
    {
        id:"ktsw",
        items:["hwtu"]
    },
    {
        id:"auuq",
        items:["rmry"]
    },
    {
        id:"asee",
        items:["gtzq"]
    },
    {
        id:"wugi",
        items:["qykr"]
    },
    {
        id:"pdmt",
        items:["otlj"]
    },
    {
        id:"cxjx",
        items:["psjy"]
    },
    {
        id:"cgsv",
        items:["oxkf"]
    },
    {
        id:"hstl",
        items:["hyen"]
    },
    {
        id:"nnft",
        items:["hdrr"]
    },
    {
        id:"ahpj",
        items:["wyad"]
    },
    {
        id:"vskb",
        items:["hngz"]
    },
    {
        id:"tpqr",
        items:["canj"]
    },
    {
        id:"gybu",
        items:["nbeo"]
    },
    {
        id:"pmgl",
        items:["izao"]
    },
    {
        id:"gmqw",
        items:["lzck"]
    },
    {
        id:"lzrt",
        items:["vjji"]
    },
    {
        id:"plqp",
        items:["kltg"]
    },
    {
        id:"rthh",
        items:["jzgt"]
    },
    {
        id:"xpvh",
        items:["vlhl"]
    },
    {
        id:"lavv",
        items:["fwqg"]
    },
    {
        id:"xvul",
        items:["anxm"]
    },
    {
        id:"nymt",
        items:["ajtf"]
    },
    {
        id:"cdxd",
        items:["rjpb"]
    },
    {
        id:"lqmc",
        items:["eudg"]
    },
    {
        id:"mgbo",
        items:["dwga"]
    },
    {
        id:"ejkd",
        items:["vcrk"]
    },
    {
        id:"rimj",
        items:["jcgr"]
    },
    {
        id:"naqb",
        items:["bern"]
    },
    {
        id:"kgpe",
        items:["zpdy"]
    },
    {
        id:"wcfx",
        items:["tudm"]
    },
    {
        id:"zneg",
        items:["biqd"]
    },
    {
        id:"kdns",
        items:["goyw"]
    },
    {
        id:"setl",
        items:["jyuy"]
    },
    {
        id:"zemk",
        items:["afce"]
    },
    {
        id:"hqrw",
        items:["mepw"]
    },
    {
        id:"hhtt",
        items:["sbfu"]
    },
    {
        id:"tfts",
        items:["twop"]
    },
    {
        id:"tiwg",
        items:["igsl"]
    },
    {
        id:"pqlx",
        items:["woiq"]
    },
    {
        id:"ssxp",
        items:["gujk"]
    },
    {
        id:"xjcm",
        items:["roar"]
    },
    {
        id:"ykjp",
        items:["lhib"]
    },
    {
        id:"feer",
        items:["xjmu"]
    },
    {
        id:"cqpy",
        items:["sloi"]
    },
    {
        id:"vfuc",
        items:["toia"]
    },
    {
        id:"ebhx",
        items:["yorc"]
    },
    {
        id:"zeyg",
        items:["aujz"]
    },
    {
        id:"duqn",
        items:["gxwt"]
    },
    {
        id:"tnmu",
        items:["dzss"]
    },
    {
        id:"ctvg",
        items:["xuku"]
    },
    {
        id:"tncw",
        items:["wlqr"]
    },
    {
        id:"kuqu",
        items:["xeqm"]
    },
    {
        id:"acad",
        items:["vkmz"]
    },
    {
        id:"xpao",
        items:["dakk"]
    },
    {
        id:"vshu",
        items:["rosw"]
    },
    {
        id:"opmi",
        items:["nebl"]
    }
];

export default records; // In-memory data store (replace with database interaction)
